spring:
  application:
    name: mscloudgateway

  cloud:
    gateway:
      locator:
        enabled: true
        lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/msjavarealm

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://msjava-eureka-user:JKHBjkhGHla@${EUREKA_SERVER}:8761/eureka