spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: msjava-eureka-user
      password: JKHBjkhGHla

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false